config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "/testing", to: "pages#testing"

  resources :users, except: [:index, :destroy]
  resources :stories do
  	resources :chapters do
      resources :lines, except: [:show] do 
        put :update_options
      end
    end
    resources :endings, except: [:index, :show]
    resources :storycharacters
    resources :play, only: [:index]
  end
  resources :characters

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete :destroy, only: [:index, :new, :create, :destroy]
    end
  end
end

app/models/storycharacter.rb
# == Schema Information
#
# Table name: storycharacters
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  character_id :bigint           not null
#  story_id     :bigint           not null
#
# Indexes
#
#  index_storycharacters_on_character_id  (character_id)
#  index_storycharacters_on_story_id      (story_id)
#
class Storycharacter < ApplicationRecord
  belongs_to :character
  belongs_to :story

  validates_uniqueness_of :character_id, scope: [:story_id]
end

app/controllers/storycharacters_controller.rb
class StorycharactersController < ApplicationController
  before_action :authenticate!
  before_action :set_story

  def index
    @characters = @story.characters
    page = params[:page] || 1

    @characters = @characters
      .page(page)
      .per(10)
  end

  def new
    @characters = @story.characters
    @story_character = Storycharacter.new
  end

  def create
    @story_character = Storycharacter.new(story_character_params.merge({story: @story}))
    if @story_character.save
      redirect_to story_storycharacters_path(@story)
    else
      render :new
    end
  end

  def destroy
  end

  private
    def set_story
      @story = Story.find(params[:story_id])
    end

    def story_character_params
      params.require(:storycharacter).permit(:character_id)
    end
end

app/views/storycharacters/_form.html.erb
<%= f.input(
  :character_id,
  required: true,
  as: :select,
  collection: current_user.characters,
  label_method: :name,
  value_method: :id,
)%>

app/views/storycharacters/index.html.erb
<%= render "layouts/title_header", title: "#{@story.title} Characters!" %>
<div class="row mt-3">
  <% @characters.each_with_index do |character, idx| %>
    <div class="col-auto">
      <div id="story-<%= character.id %>" class="link card <%= card_color(idx) %> mb-3" style="width: 18rem; height: 14rem;cursor: pointer;">
        <div class="card-header text-center">─── ･ ｡ﾟ☆: *.☽ .* :☆ﾟ. ───</div>
        <div class="card-body">
          <h5 class="card-title"><%= character.name %></h5>
          <p class="card-text"><%= character.biography %></p>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $('#story-<%= character.id %>').click(function(){
        window.location.href = "<%= edit_character_path(character) %>";
      });
    </script>
  <% end %>
</div>


<%= paginate @characters, theme: 'bootstrap4' %>

<%= link_to "back", story_path(@story) %> |
<%= link_to "new character", new_character_path(story_id: @story.id) %> |
<%= link_to "add existing character", new_story_storycharacter_path %>

app/views/storycharacters/new.html.erb
<%= render "layouts/title_header", title: "New Character " %>
<%= simple_form_for([@story, @story_character], html: { 'data-parsley-validate': true }) do |f| %>
  <%= render "form", f: f %>
  <div class="form-actions pb-2">
    <%= f.button :submit, "Create Character", class: 'btn-dating' %>
  </div>
<% end %>