config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "/testing", to: "pages#testing"

  resources :users, except: [:index, :destroy]
  resources :stories do
  	resources :chapters do
      resources :lines, except: [:show] do 
        put :update_options
      end
    end
    resources :endings, except: [:index, :show]
    resources :storycharacters
    resources :play, only: [:index]
  end
  resources :characters

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete :destroy, only: [:index, :new, :create, :destroy]
    end
  end
end

app/models/line.rb
# == Schema Information
#
# Table name: lines
#
#  id            :bigint           not null, primary key
#  emotion       :integer          default("default"), not null
#  line_type     :integer          default("chapter"), not null
#  order         :integer          not null
#  text          :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  chapter_id    :bigint           not null
#  speakeable_id :integer          not null
#
# Indexes
#
#  index_lines_on_chapter_id  (chapter_id)
#
class Line < ApplicationRecord
  validates_uniqueness_of :order, scope: :chapter_id

  enum line_type: {
  	chapter: 0,
  	option: 1,
  }

  EMOTIONS = Character::EMOTIONS.keys.each_with_object({}).with_index do |(el, acc), index|
    acc[el] = index
  end
  enum emotion: EMOTIONS

  has_one :option
  belongs_to :chapter

  def mc?
    speakeable_id == 0
  end

  def speaker_name
    if mc?
      "MC"
    else
      Character.find(speakeable_id).name
    end
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :authenticate!, except: [:update_options]
  before_action :set_story
  before_action :set_chapter
  before_action :set_line, except: [:new, :create, :index]
# bulk update for line ordering
  
  def index
    @lines = @chapter.lines.includes(:option).order(:order)
    page = params[:page] || 1

    @lines = @lines
      .page(page)
      .per(20)
  end

  def new
    @line = Line.new
    respond_with(@line)
  end

  def create
    @line = Line.new(line_params.merge({ chapter: @chapter }))

    order_number = Lines::BuildOrder.execute(chapter: @chapter, line: @line).order_number
    @line.update_attributes(order: order_number)

    ActiveRecord::Base.transaction do
      @line.save!
      if option_params.select{ |k, v| v.present? }.present?
        @option = Option.create(option_params.merge({ line: @line }))
      end
      respond_with(@line, location: -> { story_chapter_lines_path(@story, @chapter) })
    end
  rescue
    redirect_to new_story_chapter_line_path(@story, @chapter, Line.new), alert: "Failed to save line"
  end

  def update
    if @line.update(line_params)
      respond_with(@line, location: -> { story_chapter_lines_path })
    else
      render :edit
    end
  end

  def update_options
  end

  def edit
  end

  def destroy
  end

  private
    def set_story
      @story = Story.find(params[:story_id])
    end

    def set_chapter
      @chapter = @story.chapters.find(params[:chapter_id])
    end

    def set_line
      @line = @chapter.lines.find(params[:id])
    end

    def line_params
      params.require(:line).permit(
        :line_type,
        :emotion,
        :text,
        :speakeable_id,
      )
    end

    def option_params
      params[:option] = {}
      params[:option][:answers] = Answers::BuildAnswers.execute(params: params[:line][:option]).answers
      params[:option][:weights] = Answers::BuildWeights.execute(params: params[:line][:option]).weights

      params.require(:option).permit(
        weights: [],
        answers: [],
      )
    end
end

app/views/lines/_form.html.erb
<%= f.input(
  :speakeable_id,
  required: true,
  as: :select,
  collection: [
    ["MC", 0],
    *current_user.characters.map{ |c| [c.name, c.id] }
  ]
)%>
<%= f.input :text, label: "Text/Question", required: true %>
<%= f.input(
  :emotion,
  required: true,
  as: :select,
  collection: Line.emotions.keys.map {|k| [k.humanize, k]},
)%>
<!-- radio buttons? - of fontawesome emoji -->

<div class="py-2">
  <a id="option-button" class="button default ok" href="#option-answers" data-toggle="collapse" aria-expanded="false">
    make this a question
  </a>
  <div id="option-answers" class="collapse mt-4">
    <%= f.simple_fields_for(:option) do |option_f| %>
      <% Option::OPTIONS.zip(Option::WEIGHTS).each do |answer, weight| %>
        <div class="row">
          <div class="col-10">
            <%= option_f.input answer, required: true %>
          </div>
          <div class="col-2">
            <%= option_f.input(
              weight,
              required: true,
              as: :integer,
              input_html: { max: 10, min: -10 },
            )%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<!-- show preview? -->

app/views/lines/edit.html.erb
<%= render "layouts/title_header", title: "Edit Line" %>
<%= simple_form_for([@story, @chapter, @line], html: { 'data-parsley-validate': true}) do |f| %>
  <%= render "form", f: f %>
  <div class="form-actions pb-2">
    <%= f.button :submit, class: 'btn-dating' %>
  </div>
<% end %>

<a href="<%= story_chapter_path(@story, @chapter) %>">
  <span class="arrow flip">&#x27b8;</span>
</a>

app/views/lines/index.html.erb
<%= render "layouts/title_header", title: "#{@story.title} - #{@chapter.title}" %>
<% @lines.each do |line| %>
    <!-- figure out weirdness later -->
    <!-- text message bubble, look up css -->
  <div class="my-3 hover-hidden">
    <% if line.mc? %>
      <div class="row">
        <div class="col-auto ml-auto">
          <a class="hidden" href="<%= edit_story_chapter_line_path(@story, @chapter, line) %>">
            <i class="fas fa-pen-fancy"></i> edit
          </a>
        </div>
        <div class="col-6">
          <div class="card bg-lavender text-white">
            <div class="m-3">
              <%= line.text %>
            </div>
          </div>
        </div>
        <div class="col-auto" style="align-self: flex-end;">
          profile
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-auto" style="align-self: flex-end;">
          EMO
        </div>
        <div class="col-6">
          <b><%= line.speaker_name %></b><br/>
          <div class="card bg-hot-pink text-white">
            <div class="m-3">
              <%= line.text %>
            </div>
          </div>
        </div>
        <div class="col-auto">
          <a class="hidden" href="<%= edit_story_chapter_line_path(@story, @chapter, line) %>">
            <i class="fas fa-pen-fancy"></i> edit
          </a>
        </div>
      </div>
    <% end %>
  </div>
  <% if line.option.present? %>
    <div class="row">
      <div class="col-1"></div>
      <% line.option.answers.each do |answer| %>
        <div class="col-auto text-center">
          <span class="badge bg-white border px-4 py-2" style="border-radius: 20px;">
            <%= answer %>
          </span>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= paginate @lines, theme: 'bootstrap4' %>
<div class="my-4">
  <%= link_to "back", story_chapters_path(@story) %> |
  <%= link_to "edit chapter", edit_story_chapter_path(@story, @chapter) %> |
  <%= link_to "new line", new_story_chapter_line_path(@story, @chapter) %>
</div>

<!-- option after line -->

app/views/lines/new.html.erb
<%= render "layouts/title_header", title: "New Line" %>
<%= simple_form_for([@story, @chapter, @line], html: { 'data-parsley-validate': true}) do |f| %>
  <%= render "form", f: f %>
  <div class="form-actions pb-2">
    <%= f.button :submit, class: 'btn-dating' %>
  </div>
<% end %>

<a href="<%= story_chapter_path(@story, @chapter) %>">
  <span class="arrow flip">&#x27b8;</span>
</a>