config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "/testing", to: "pages#testing"

  resources :users, except: [:index, :destroy]
  resources :stories do
  	resources :chapters do
      resources :lines, except: [:show] do 
        put :update_options
      end
    end
    resources :endings, except: [:index, :show]
    resources :storycharacters
    resources :play, only: [:index]
  end
  resources :characters

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete :destroy, only: [:index, :new, :create, :destroy]
    end
  end
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id          :bigint           not null, primary key
#  description :text
#  status      :integer          default("draft"), not null
#  title       :string           not null
#  uid         :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_stories_on_user_id  (user_id)
#
class Story < ApplicationRecord
  belongs_to :user
  has_many :chapters

  has_many :storycharacters
  has_many :characters, through: :storycharacters

  validates_uniqueness_of :uid
  before_save :rand_uid

  enum status: {
    draft: 0,
    published: 1,
  }

  def mini_description
    max_size = 100
    if description.size > max_size
      "#{description[0..100]}..."
    else
      description 
    end
  end

  def rand_uid
    all_array = ("A"..."Z").to_a + (1..9).to_a.map { |c| c.to_s }
    all_array.delete("I")
    all_array.delete("O")
    self.uid = (0..6).map { |i| all_array.sample }.join
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate!
  before_action :set_story, except: [:index, :new, :create]

  def index
    @stories = current_user.stories
    page = params[:page] || 1

    @stories = @stories
      .page(page)
      .per(10)
  end

  def new
    @story = Story.new
    respond_with(@story)
  end

  def create
    result = Stories::Create.call(story_params.merge({ user: current_user }))
    if result.success?
      @story = result.story
      respond_with(@story, location: -> { stories_path })
    else
      render :new
    end
  end

  def show
  end

  def update
  end

  def edit
  end

  private
    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:story).permit(
        :id,
        :title,
        :description,
        :status,
      )
    end
end

app/views/stories/_form.html.erb
<%= f.input :title, required: true %>
<%= f.input :description %>
<%= f.input(
  :status,
  as: :select,
  collection: Story.statuses.keys.map {|k| [k.humanize, k]},
  required: true,
  input_html: {
    class: "w-50"
  }
)%>

app/views/stories/edit.html.erb
<%= render "layouts/title_header", title: "Edit Dating Sim" %>
<%= simple_form_for(@story, html: { 'data-parsley-validate': true}) do |f| %>
  <%= render "form", f: f %>
  <div class="form-actions pb-2">
    <%= f.button :submit, "Update Dating Sim", class: 'btn-dating' %>
  </div>
<% end %>

<a href="<%= story_path(@story) %>">
  <span class="arrow flip">&#x27b8;</span>
</a>

app/views/stories/index.html.erb
<%= render "layouts/title_header", title: "Dating Sims!" %>
<div class="row mt-3">
  <% @stories.each_with_index do |story, idx| %>
    <div class="col-auto">
      <div id="story-<%= story.id %>" class="link card <%= card_color(idx) %> mb-3" style="width: 18rem; height: 14rem;cursor: pointer;">
        <div class="card-header text-center">─── ･ ｡ﾟ☆: *.☽ .* :☆ﾟ. ───</div>
        <div class="card-body">
          <h5 class="card-title"><%= story.title %></h5>
          <p class="card-text">
            <%= story.mini_description %>
            <br/>
            <%= story.status.capitalize %>  
          </p>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $('#story-<%= story.id %>').click(function(){
        window.location.href = "<%= story_path(story) %>";
      });
    </script>
  <% end %>
</div>

<%= paginate @stories, theme: 'bootstrap4' %>

<%= link_to "new", new_story_path %>

app/views/stories/new.html.erb
<%= render "layouts/title_header", title: "New Dating Sim" %>
<%= simple_form_for(@story, html: { 'data-parsley-validate': true}) do |f| %>
  <%= render "form", f: f, story: @story %>
  <div class="form-actions pb-2">
    <%= f.button :submit, "Create Dating Sim", class: 'btn-dating' %>
  </div>
<% end %>

app/views/stories/show.html.erb
<%= render "layouts/title_header", title: @story.title %>
<p><%= @story.description %></p>

<div class="row">
  <div class="col-auto">
    <div id="character" class="link card text-white bg-lavender mb-3" style="width: 18rem; height: 14rem;cursor: pointer;">
      <div class="card-header text-center">─── ･ ｡ﾟ☆: *.☽ .* :☆ﾟ. ───</div>
      <div class="card-body">
        <h5 class="card-title">
          <i class="fas fa-dove"></i> Characters <i class="fas fa-dove"></i>
        </h5>
        <p class="card-text">
          <% limit_size = @story.characters.size > 4 ? 3 : 4 %>
          <% @story.characters.limit(limit_size).each do |character| %>
            <%= character.name %> <br/>
          <% end %>
          <%= limit_size == 3 ? "and more.." : "" %>
        </p>
      </div>
    </div>
  </div>
  <!-- activate characters for story -->
  <div class="col-auto">
    <div id="chapter" class="link card bg-yellow text-white mb-3" style="width: 18rem; height: 14rem;cursor: pointer;">
      <div class="card-header text-center">─── ･ ｡ﾟ☆: *.☽ .* :☆ﾟ. ───</div>
      <div class="card-body">
        <h5 class="card-title">
          <i class="fas fa-star"></i> Chapters <i class="fas fa-star"></i>
        </h5>
        <p class="card-text">
          <%= "#{chapter_size = @story.chapters.size} #{chapter_size > 1 ? "chapters" : "chapter"}" %><br/>
          FILL LATER : # of endings
        </p>
      </div>
    </div>
  </div>
  <div class="col-auto">
    <div id="story" class="link card bg-orange text-white mb-3" style="width: 18rem; height: 14rem;cursor: pointer;">
      <div class="card-header text-center">─── ･ ｡ﾟ☆: *.☽ .* :☆ﾟ. ───</div>
      <div class="card-body">
        <h5 class="card-title"> <i class="fas fa-chess-knight fa-flip-horizontal"></i> Edit Dating Sim <i class="fas fa-chess-knight"></i></h5>
        <p class="card-text">
          <%= @story.status.humanize %>  
        </p>
      </div>
    </div>
  </div>
  <div class="col-auto">
    <div id="play" class="link card bg-hot-pink text-white mb-3" style="width: 18rem; height: 14rem;cursor: pointer;">
      <div class="card-header text-center">─── ･ ｡ﾟ☆: *.☽ .* :☆ﾟ. ───</div>
      <div class="card-body">
        <h5 class="card-title"> <i class="fas fa-chess-knight fa-flip-horizontal"></i> Play [WIP] <i class="fas fa-chess-knight"></i></h5>
        <p class="card-text">
          Play Online <br/>
          Download
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to "back", stories_path %>

<script type="text/javascript">
  $('#character').click(function(){
    window.location.href = "<%= story_storycharacters_path(@story) %>";
  });
  $('#chapter').click(function(){
    window.location.href = "<%= story_chapters_path(@story) %>";
  });
  $('#story').click(function(){
    window.location.href = "<%= edit_story_path(@story) %>";
  });
</script>