config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "/testing", to: "pages#testing"

  resources :users, except: [:index, :destroy]
  resources :stories do
  	resources :chapters do
      resources :lines, except: [:show] do 
        put :update_options
      end
    end
    resources :endings, except: [:index, :show]
    resources :storycharacters
    resources :play, only: [:index]
  end
  resources :characters

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete :destroy, only: [:index, :new, :create, :destroy]
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-pink bg-white shadow-sm">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="m-0"><3 Dating Sim Maker</ul>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <% if current_user.present? %>
        <li class="nav-item active">
          <a class="nav-link" href="<%= user_path(current_user) %>"><i class="far fa-meh-rolling-eyes"></i></a>
        </li>
      <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="<%= new_session_url %>">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="bg-pink" id="sidebar-wrapper">
  <div class="sidebar-heading mb-4"></div>
  <div class="list-group list-group-flush">
    <a href="<%= stories_url %>" class="<%= controller_name == "stories" ? 'active' : '' %> custom-list-group-item custom-list-group-item-action bg-pink">S</a>
    <a href="<%= characters_path %>" class="<%= controller_name == "characters" ? 'active' : '' %> custom-list-group-item custom-list-group-item-action bg-pink">C</a>
    <a href="#" class="custom-list-group-item custom-list-group-item-action bg-pink">H</a>
    <a href="#" class="custom-list-group-item custom-list-group-item-action bg-pink">T</a>
  </div>
</div>

app/views/layouts/_title_header.html.erb
<% content_for(:title, title) %>
<% header_size ||= 3 %>
<%= content_tag("h#{header_size}", content_for(:title)) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title).presence || "Dating Sim Maker" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c564821872.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <link href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css"></link>
    <script src="https://parsleyjs.org/dist/parsley.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Nunito&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex" id="wrapper">
      <%= render "layouts/sidebar" %>
      <div id="page-content-wrapper">
        <%= render "layouts/navbar" %>
        <% if flash[:notice].present? %>
          <div class="alert alert-info alert-dismissible m-2">
            <span class="glyphicon glyphicon-info-sign"></span>
            <%= flash[:notice].html_safe %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <% if flash[:alert].present? %>
          <div class="alert bg-hot-pink text-white alert-dismissible m-2">
            <span class="glyphicon glyphicon-exclamation-sign"></span>
            <%= flash[:alert].html_safe %>
            <% if flash.key?(:errors) %>
              <ul>
                <% flash[:errors].each do |e| %>
                  <li><%= e %></li>
                <% end %>
              </ul>
            <% end %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <div class="container-fluid p-4">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/story.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title).presence || "Dating Sim Maker" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'story-bundle' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c564821872.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <link href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css"></link>
    <script src="https://parsleyjs.org/dist/parsley.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Nunito&family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex" id="wrapper">
      <%= render "layouts/sidebar" %>
      <div id="page-content-wrapper">
        <%= render "layouts/navbar" %>
        <% if flash[:notice].present? %>
          <div class="alert alert-info alert-dismissible m-2">
            <span class="glyphicon glyphicon-info-sign"></span>
            <%= flash[:notice].html_safe %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <% if flash[:alert].present? %>
          <div class="alert bg-hot-pink text-white alert-dismissible m-2">
            <span class="glyphicon glyphicon-exclamation-sign"></span>
            <%= flash[:alert].html_safe %>
            <% if flash.key?(:errors) %>
              <ul>
                <% flash[:errors].each do |e| %>
                  <li><%= e %></li>
                <% end %>
              </ul>
            <% end %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <div class="container-fluid p-4">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>